<?php
// Enable error reporting for debugging
error_reporting(E_ALL);
ini_set('display_errors', 1);

try {
    if (!isset($_GET['id'])) {
        throw new Exception('Website ID not provided');
    }
    
    $websiteId = $_GET['id'];
    $websiteDir = "generated_websites/$websiteId";
    
    // Check if website directory exists
    if (!file_exists($websiteDir)) {
        throw new Exception('Website not found');
    }
    
    // Load metadata
    $metadataFile = "$websiteDir/metadata.json";
    if (!file_exists($metadataFile)) {
        throw new Exception('Website metadata not found');
    }
    
    $metadata = json_decode(file_get_contents($metadataFile), true);
    $websiteName = $metadata['websiteName'] ?? 'website';
    
    // Create ZIP file
    $zipFilename = sanitizeFilename($websiteName) . '_' . date('Y-m-d_H-i-s') . '.zip';
    $zipPath = "downloads/$zipFilename";
    
    // Create downloads directory if it doesn't exist
    if (!file_exists('downloads')) {
        mkdir('downloads', 0755, true);
    }
    
    // Create ZIP archive
    $zip = new ZipArchive();
    $result = $zip->open($zipPath, ZipArchive::CREATE | ZipArchive::OVERWRITE);
    
    if ($result !== TRUE) {
        throw new Exception('Failed to create ZIP file: ' . $result);
    }
    
    // Add all files to ZIP
    addDirectoryToZip($zip, $websiteDir, '');
    
    // Add README file
    $readmeContent = generateReadmeContent($metadata);
    $zip->addFromString('README.md', $readmeContent);
    
    $zip->close();
    
    // Set headers for download
    header('Content-Type: application/zip');
    header('Content-Disposition: attachment; filename="' . $zipFilename . '"');
    header('Content-Length: ' . filesize($zipPath));
    header('Cache-Control: no-cache, must-revalidate');
    header('Expires: 0');
    
    // Output file and delete it
    readfile($zipPath);
    unlink($zipPath);
    
} catch (Exception $e) {
    http_response_code(500);
    echo 'Error: ' . $e->getMessage();
}

function addDirectoryToZip($zip, $dir, $zipDir) {
    $files = scandir($dir);
    
    foreach ($files as $file) {
        if ($file === '.' || $file === '..') {
            continue;
        }
        
        $filePath = "$dir/$file";
        $zipPath = $zipDir ? "$zipDir/$file" : $file;
        
        if (is_dir($filePath)) {
            $zip->addEmptyDir($zipPath);
            addDirectoryToZip($zip, $filePath, $zipPath);
        } else {
            // Skip metadata.json file
            if ($file === 'metadata.json') {
                continue;
            }
            $zip->addFile($filePath, $zipPath);
        }
    }
}

function sanitizeFilename($filename) {
    // Remove or replace invalid characters
    $filename = preg_replace('/[^a-zA-Z0-9\-_\.]/', '_', $filename);
    $filename = preg_replace('/_{2,}/', '_', $filename);
    $filename = trim($filename, '_');
    
    return $filename ?: 'website';
}

function generateReadmeContent($metadata) {
    $websiteName = $metadata['websiteName'] ?? 'Website';
    $websiteType = $metadata['websiteType'] ?? 'website';
    $ownerName = $metadata['ownerName'] ?? 'Owner';
    $createdAt = $metadata['createdAt'] ?? date('Y-m-d H:i:s');
    $pages = $metadata['pages'] ?? [];
    
    $readme = "# $websiteName\n\n";
    $readme .= "**Website Type:** " . ucfirst($websiteType) . "\n";
    $readme .= "**Owner:** $ownerName\n";
    $readme .= "**Generated:** $createdAt\n";
    $readme .= "**Generated by:** WebGenX - AI-Powered Website Generator\n\n";
    
    $readme .= "## About\n\n";
    $readme .= "This website was automatically generated using WebGenX, an AI-powered website generator. ";
    $readme .= "The website includes a complete folder structure with responsive design and modern styling.\n\n";
    
    $readme .= "## Structure\n\n";
    $readme .= "```\n";
    $readme .= "├── index.php          # Home page\n";
    $readme .= "├── header.php         # Common header\n";
    $readme .= "├── footer.php         # Common footer\n";
    
    foreach ($pages as $page) {
        if ($page !== 'home') {
            $readme .= "├── $page.php" . str_repeat(' ', 14 - strlen($page)) . "# " . ucfirst($page) . " page\n";
        }
    }
    
    $readme .= "├── css/\n";
    $readme .= "│   └── style.css      # Main stylesheet\n";
    $readme .= "├── js/\n";
    $readme .= "│   └── script.js      # JavaScript functionality\n";
    $readme .= "├── images/            # Image assets\n";
    $readme .= "└── assets/            # Other assets\n";
    $readme .= "```\n\n";
    
    $readme .= "## Setup Instructions\n\n";
    $readme .= "1. **Web Server:** Upload all files to your web server\n";
    $readme .= "2. **Local Development:** Use a local server (XAMPP, WAMP, etc.)\n";
    $readme .= "3. **Access:** Open `index.php` in your web browser\n\n";
    
    $readme .= "## Features\n\n";
    $readme .= "- ✅ Responsive design (mobile-friendly)\n";
    $readme .= "- ✅ Modern Bootstrap 5 styling\n";
    $readme .= "- ✅ Font Awesome icons\n";
    $readme .= "- ✅ Cross-browser compatibility\n";
    $readme .= "- ✅ SEO-friendly structure\n";
    $readme .= "- ✅ Clean, semantic HTML5\n";
    $readme .= "- ✅ Smooth animations and transitions\n\n";
    
    $readme .= "## Pages Included\n\n";
    foreach ($pages as $page) {
        $readme .= "- **" . ucfirst($page) . ":** ";
        switch ($page) {
            case 'home':
                $readme .= "Main landing page with hero section and overview\n";
                break;
            case 'about':
                $readme .= "Detailed information about the owner/business\n";
                break;
            case 'projects':
                $readme .= "Portfolio showcase and project details\n";
                break;
            case 'contact':
                $readme .= "Contact form and contact information\n";
                break;
            case 'blog':
                $readme .= "Blog posts and articles\n";
                break;
            case 'gallery':
                $readme .= "Image gallery and visual content\n";
                break;
            default:
                $readme .= "Custom page content\n";
        }
    }
    
    $readme .= "\n## Customization\n\n";
    $readme .= "- **Styling:** Modify `css/style.css` to change colors, fonts, and layout\n";
    $readme .= "- **Content:** Edit individual PHP files to update content\n";
    $readme .= "- **Images:** Replace placeholder images in the `images/` folder\n";
    $readme .= "- **Functionality:** Add custom JavaScript to `js/script.js`\n\n";
    
    $readme .= "## Support\n\n";
    $readme .= "This website was generated by WebGenX. For questions about customization ";
    $readme .= "or modifications, consult web development resources or hire a developer.\n\n";
    
    $readme .= "---\n";
    $readme .= "*Generated with ❤️ by WebGenX - AI-Powered Website Generator*\n";
    
    return $readme;
}
?>
